# Generated by Django 5.2.10 on 2026-01-18 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_location_tour_end_date_tour_start_date_tour_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='tours.location'),
        ),
    ]
