# Generated by Django 5.2.10 on 2026-01-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tour_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/images/'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
