# Generated by Django 5.2.10 on 2026-01-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tourimage_image_alter_tourimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='locations/images/'),
        ),
        migrations.AddField(
            model_name='location',
            name='image_url',
            field=models.URLField(blank=True, help_text='Fallback if image is not uploaded'),
        ),
    ]
