# Generated by Django 5.2.10 on 2026-01-24 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_location_description_location_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='image_url',
        ),
    ]
