# Generated by Django 5.2.10 on 2026-01-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_remove_location_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image_url',
            field=models.URLField(blank=True, help_text='Fallback/External URL'),
        ),
    ]
