# Generated by Django 5.2.10 on 2026-01-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_location_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='quotation_file',
            field=models.FileField(blank=True, help_text='Upload PDF quotation file', null=True, upload_to='locations/quotations/'),
        ),
    ]
