# Generated by Django 5.2.13 on 2026-04-18 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_enable_unaccent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description_md',
            field=models.TextField(blank=True, help_text='Markdown description'),
        ),
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='TourItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text='Day index. Day 0 = one day before tour start')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content_md', models.TextField(blank=True, help_text='Markdown itinerary content')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='tours.tour')),
            ],
            options={
                'ordering': ['day_number'],
                'constraints': [models.UniqueConstraint(fields=('tour', 'day_number'), name='uniq_tour_itinerary_day')],
            },
        ),
    ]
