# Generated by Codex on 2026-04-18

from datetime import timedelta

from django.db import migrations


def _build_title(tour, day_number: int) -> str:
    if tour.start_date:
        day_date = tour.start_date + timedelta(days=day_number - 1)
        return f"Day {day_number} - {day_date.strftime('%d/%m/%Y')}"
    return f"Day {day_number}"


def forwards(apps, schema_editor):
    Tour = apps.get_model("tours", "Tour")
    TourItineraryDay = apps.get_model("tours", "TourItineraryDay")

    for tour in Tour.objects.all().iterator():
        if tour.start_date and tour.end_date and tour.end_date >= tour.start_date:
            total_days = (tour.end_date - tour.start_date).days + 2
            day_numbers = list(range(total_days))
        else:
            day_numbers = [0] if (tour.itinerary_md or "").strip() else []

        if not day_numbers:
            continue

        created_day_zero = False
        for day_number in day_numbers:
            day, created = TourItineraryDay.objects.get_or_create(
                tour=tour,
                day_number=day_number,
                defaults={
                    "title": _build_title(tour, day_number),
                },
            )
            if not day.title:
                day.title = _build_title(tour, day_number)
                day.save(update_fields=["title"])

            if day_number == 0 and created:
                created_day_zero = True

        if created_day_zero and (tour.itinerary_md or "").strip():
            TourItineraryDay.objects.filter(tour=tour, day_number=0).update(
                content_md=tour.itinerary_md
            )


def backwards(apps, schema_editor):
    TourItineraryDay = apps.get_model("tours", "TourItineraryDay")
    TourItineraryDay.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0011_tour_description_md_tour_price_touritineraryday"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
