# Generated by Django 5.2.13 on 2026-04-25 08:37

import django.core.validators
from django.db import migrations, models


def seed_location_audiences(apps, schema_editor):
    location_audience = apps.get_model('tours', 'LocationAudience')
    defaults = [
        {
            'code': 'beginner',
            'title': 'Người mới',
            'description': 'Lộ trình dễ tiếp cận, phù hợp để làm quen với trekking và xây nền thể lực.',
            'sort_order': 1,
        },
        {
            'code': 'intermediate',
            'title': 'Trung cấp',
            'description': 'Hành trình có độ dốc và thời lượng rõ rệt, phù hợp với người đã có nền tảng vận động cơ bản.',
            'sort_order': 2,
        },
        {
            'code': 'push_limit',
            'title': 'Người muốn vượt giới hạn',
            'description': 'Hành trình chinh phục đỉnh cao, thử thách thể lực và ý chí rõ ràng nhất.',
            'sort_order': 3,
        },
    ]

    for item in defaults:
        location_audience.objects.update_or_create(
            code=item['code'],
            defaults={
                'title': item['title'],
                'description': item['description'],
                'sort_order': item['sort_order'],
            },
        )


def remove_seeded_location_audiences(apps, schema_editor):
    location_audience = apps.get_model('tours', 'LocationAudience')
    location_audience.objects.filter(
        code__in=['beginner', 'intermediate', 'push_limit']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_backfill_tour_itinerary_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('push_limit', 'Push Limit')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(
            seed_location_audiences,
            reverse_code=remove_seeded_location_audiences,
        ),
        migrations.AddField(
            model_name='location',
            name='home_display_name',
            field=models.CharField(blank=True, help_text='Homepage display name override', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='home_feature_order',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Homepage featured routes order from 1 to 4', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='location',
            name='home_feature_summary',
            field=models.TextField(blank=True, help_text='Homepage featured routes summary'),
        ),
        migrations.AddField(
            model_name='location',
            name='home_subtitle',
            field=models.CharField(blank=True, help_text='Homepage subtitle shown under the title', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='suitable_audiences',
            field=models.ManyToManyField(blank=True, help_text='Suitable audiences for this location', related_name='locations', to='tours.locationaudience'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('home_feature_order__isnull', False)), fields=('home_feature_order',), name='uniq_location_home_feature_order'),
        ),
    ]
